# Generated by Django 2.2.12 on 2022-07-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continents', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countrie', models.CharField(max_length=100)),
                ('continents', models.ManyToManyField(to='holidays.Continents')),
            ],
        ),
        migrations.CreateModel(
            name='HolidayRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.ManyToManyField(to='holidays.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='TypeHoliday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_hol', models.CharField(max_length=100)),
                ('temp', models.CharField(max_length=100)),
                ('loaction', models.ManyToManyField(to='holidays.Location')),
                ('ref', models.ManyToManyField(to='holidays.HolidayRef')),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HotelName', models.CharField(max_length=100)),
                ('Area', models.CharField(max_length=100)),
                ('StarRating', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('PricePerPerNight', models.CharField(max_length=100)),
                ('loaction', models.ManyToManyField(to='holidays.Location')),
                ('ref', models.ManyToManyField(to='holidays.HolidayRef')),
                ('type_hol', models.ManyToManyField(to='holidays.TypeHoliday')),
            ],
        ),
        migrations.AddField(
            model_name='countries',
            name='ref',
            field=models.ManyToManyField(to='holidays.HolidayRef'),
        ),
        migrations.AddField(
            model_name='continents',
            name='ref',
            field=models.ManyToManyField(to='holidays.HolidayRef'),
        ),
    ]
