# Generated by Django 2.2.12 on 2022-07-18 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countries',
            old_name='countrie',
            new_name='countries',
        ),
        migrations.RenameField(
            model_name='holiday',
            old_name='Area',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='holiday',
            old_name='HotelName',
            new_name='atarRating',
        ),
        migrations.RenameField(
            model_name='holiday',
            old_name='Location',
            new_name='hotelName',
        ),
        migrations.RenameField(
            model_name='holiday',
            old_name='PricePerPerNight',
            new_name='pricePerPerNight',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='ref',
            new_name='Location',
        ),
        migrations.RemoveField(
            model_name='continents',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='countries',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='StarRating',
        ),
    ]
