# Generated by Django 4.0.6 on 2022-07-18 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0002_auto_20220718_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='loaction',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='location',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='typeholiday',
            name='loaction',
        ),
        migrations.RemoveField(
            model_name='typeholiday',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='typeholiday',
            name='temp',
        ),
        migrations.AddField(
            model_name='holiday',
            name='location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='holidays.location'),
        ),
        migrations.AddField(
            model_name='location',
            name='location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='holidays.countries'),
        ),
        migrations.RemoveField(
            model_name='countries',
            name='continents',
        ),
        migrations.AddField(
            model_name='countries',
            name='continents',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='holidays.continents'),
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='type_hol',
        ),
        migrations.AddField(
            model_name='holiday',
            name='type_hol',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='holidays.typeholiday'),
        ),
        migrations.DeleteModel(
            name='HolidayRef',
        ),
    ]
