# Generated by Django 4.0.6 on 2022-07-18 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0003_temperature_remove_holiday_loaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='continents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holidays.continents'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holidays.location'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='type_hol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holidays.typeholiday'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holidays.countries'),
        ),
    ]
