# Generated by Django 4.0.6 on 2022-07-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0004_alter_countries_continents_alter_holiday_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holiday',
            old_name='atarRating',
            new_name='satarRating',
        ),
    ]
